services:
  derpprobe:
    image: ghcr.io/helloworlde/tailscale-derpprober:main
    container_name: derpprobe
    hostname: derpprobe
    restart: unless-stopped
    environment:
      # Use the absolute path mounted in volumes
      - DERP_MAP=file:///config/derp.json
    ports:
      - "8030:8030"
    volumes:
      # Change the left part to your local directory where derp.json is located
      # For example: ./config:/config
      - ./config:/config
